apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - ../../base/strimzi      # installs the Strimzi operator
  - ../../base/kafka        # installs the Kafka cluster CR