apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kafka-platform
  source:
    repoURL: https://github.com/aliaksandr-budnikau/kafka-lag-exporter-gitops.git
    targetRevision: main
    path: infrastructure/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m