apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kafka-lag-exporter
      app.kubernetes.io/managed-by: argocd

images:
  - name: kafka-lag-exporter
    newName: host.docker.internal:5000/kafka-lag-exporter
    newTag: v1.0.0