apiVersion: v1
kind: Service
metadata:
  name: kafka-lag-exporter
  labels:
    app: kafka-lag-exporter
spec:
  selector:
    app: kafka-lag-exporter
  ports:
    - port: 8080
      targetPort: 8080
      name: metrics