apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-lag-exporter
spec:
  selector:
    matchLabels:
      app: kafka-lag-exporter
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics